import {
    StyleSheet,
} from "react-native";

export const SettingsStyles = (colors: any) => {
    return StyleSheet.create({
        scroll: { flex: 1 },
        content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 20 },
        title: { fontSize: 24, fontWeight: "800", color: colors.foreground, marginBottom: 4 },
        card: {
            backgroundColor: colors.surface,
            borderRadius: 16,
            paddingHorizontal: 16,
            paddingVertical: 4,
            borderWidth: 1,
            borderColor: colors.border,
        },
        goalRow: { flexDirection: "row", alignItems: "center", paddingVertical: 12 },
        goalLabel: { fontSize: 15, fontWeight: "600" },
        goalHint: { fontSize: 12, marginTop: 2 },
        goalInput: {
            borderWidth: 1,
            borderRadius: 10,
            paddingHorizontal: 12,
            paddingVertical: 8,
            fontSize: 20,
            fontWeight: "700",
            width: 72,
            textAlign: "center",
        },
        goalValueButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            paddingHorizontal: 14,
            paddingVertical: 8,
            borderRadius: 12,
        },
        goalValue: { fontSize: 22, fontWeight: "800" },
        goalEdit: { fontSize: 16 },
        goalProgress: { paddingBottom: 12 },
        progressBarBg: { height: 6, borderRadius: 3, overflow: "hidden", marginBottom: 6 },
        progressBarFill: { height: "100%", borderRadius: 3 },
        goalProgressText: { fontSize: 12 },
        notifRow: {
            flexDirection: "row",
            alignItems: "center",
            paddingVertical: 14,
        },
        notifLabel: { fontSize: 15, fontWeight: "600" },
        notifHint: { fontSize: 12, marginTop: 2 },
        notifHourRow: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            paddingVertical: 12,
            borderTopWidth: 1,
        },
        notifHourInput: { flexDirection: "row", alignItems: "center", gap: 8 },
        hourInput: {
            borderWidth: 1,
            borderRadius: 10,
            paddingHorizontal: 12,
            paddingVertical: 8,
            fontSize: 20,
            fontWeight: "700",
            width: 60,
            textAlign: "center",
        },
        hourLabel: { fontSize: 14 },
        langRow: { flexDirection: "row", gap: 8, paddingVertical: 12 },
        langButton: {
            flex: 1,
            alignItems: "center",
            paddingVertical: 10,
            borderRadius: 12,
            borderWidth: 1.5,
            gap: 4,
        },
        langFlag: { fontSize: 22 },
        langLabel: { fontSize: 11, fontWeight: "700" },
        shopItem: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            paddingVertical: 14,
        },
        shopItemLeft: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1 },
        shopItemEmoji: { fontSize: 24 },
        shopItemTitle: { fontSize: 15, fontWeight: "600" },
        shopItemDesc: { fontSize: 12, marginTop: 2 },
        shopItemPrice: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 10 },
        shopItemPriceText: { fontSize: 14, fontWeight: "700" },
        shopItemDone: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 14 },
        shopItemDoneText: { fontSize: 15, fontWeight: "600" },
        divider: { height: 1, marginVertical: 4 },
        gemsBalanceRow: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            paddingVertical: 12,
        },
        gemsBalance: { fontSize: 17, fontWeight: "700" },
        goShopButton: {
            paddingHorizontal: 16,
            paddingVertical: 8,
            borderRadius: 12,
        },
        goShopText: { color: "#FFFFFF", fontSize: 13, fontWeight: "700" },
        aboutButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: 12,
            padding: 16,
            borderRadius: 16,
            borderWidth: 1,
        },
        aboutEmoji: { fontSize: 24 },
        aboutTitle: { fontSize: 15, fontWeight: "700" },
        aboutSubtitle: { fontSize: 12, marginTop: 2 },
        aboutArrow: { fontSize: 22, fontWeight: "300" },
        dangerButton: {
            padding: 16,
            borderRadius: 16,
            alignItems: "center",
            borderWidth: 1,
        },
        dangerButtonText: { fontSize: 15, fontWeight: "700" },
    });
}