import {
    StyleSheet,
} from "react-native";

export const RunSummaryStyles = (colors: any) => {
    return StyleSheet.create({
        container: { flex: 1 },
        errorText: { fontSize: 16, textAlign: "center", marginTop: 100 },
        backLink: { fontSize: 15, textAlign: "center", marginTop: 16, fontWeight: "600" },
        celebrationHeader: {
            paddingTop: 60,
            paddingBottom: 32,
            paddingHorizontal: 24,
            alignItems: "center",
        },
        confetti: { marginBottom: 8 },
        confettiText: { fontSize: 24 },
        phoenixEmoji: { fontSize: 80, marginBottom: 12 },
        celebrationTitle: {
            fontSize: 26,
            fontWeight: "900",
            color: "#FFFFFF",
            textAlign: "center",
            marginBottom: 6,
        },
        celebrationSubtitle: {
            fontSize: 16,
            color: "#FFFFFF99",
            textAlign: "center",
            marginBottom: 16,
        },
        gemsEarned: {
            backgroundColor: "#FFFFFF30",
            paddingHorizontal: 20,
            paddingVertical: 8,
            borderRadius: 20,
            marginBottom: 16,
        },
        gemsEarnedText: {
            color: "#FFFFFF",
            fontSize: 16,
            fontWeight: "700",
        },
        progressContainer: { width: "100%", alignItems: "center" },
        progressBar: {
            width: "100%",
            height: 8,
            backgroundColor: "#FFFFFF30",
            borderRadius: 4,
            overflow: "hidden",
            marginBottom: 6,
        },
        progressFill: {
            height: "100%",
            backgroundColor: "#FFFFFF",
            borderRadius: 4,
        },
        progressText: { color: "#FFFFFF99", fontSize: 12 },
        metricsCard: {
            margin: 16,
            borderRadius: 20,
            padding: 20,
            borderWidth: 1,
        },
        metricsTitle: { fontSize: 17, fontWeight: "700", marginBottom: 16 },
        metricsGrid: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: 8,
        },
        mapCard: {
            marginHorizontal: 16,
            marginBottom: 16,
            borderRadius: 20,
            padding: 16,
            borderWidth: 1,
            overflow: "hidden",
        },
        map: {
            width: "100%",
            height: 200,
            borderRadius: 12,
            marginTop: 8,
        },
        adButton: {
            marginHorizontal: 16,
            marginBottom: 12,
            borderRadius: 16,
            padding: 16,
            borderWidth: 1.5,
            flexDirection: "row",
            alignItems: "center",
            gap: 12,
        },
        adEmoji: { fontSize: 28 },
        adInfo: { flex: 1 },
        adTitle: { fontSize: 15, fontWeight: "700" },
        adSubtitle: { fontSize: 12, marginTop: 2 },
        adBadge: {
            paddingHorizontal: 10,
            paddingVertical: 6,
            borderRadius: 12,
            fontSize: 13,
            fontWeight: "700",
            overflow: "hidden",
        },
        adWatchedBadge: {
            marginHorizontal: 16,
            marginBottom: 12,
            borderRadius: 16,
            padding: 14,
            borderWidth: 1,
            alignItems: "center",
        },
        adWatchedText: { fontSize: 14, fontWeight: "600" },
        motivationCard: {
            marginHorizontal: 16,
            marginBottom: 16,
            borderRadius: 16,
            padding: 16,
            borderWidth: 1,
        },
        motivationText: {
            fontSize: 15,
            fontWeight: "700",
            textAlign: "center",
            lineHeight: 22,
        },
        homeButton: {
            marginHorizontal: 16,
            paddingVertical: 16,
            borderRadius: 16,
            alignItems: "center",
        },
        homeButtonText: {
            color: "#FFFFFF",
            fontSize: 17,
            fontWeight: "700",
        },
    });
}
