import {
    StyleSheet,
} from "react-native";

export const BmiStyles = (colors: any) => {
    return StyleSheet.create({
        scroll: { flex: 1 },
        content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 20 },
        title: { fontSize: 24, fontWeight: "800", color: colors.foreground, marginBottom: 4 },
        subtitle: { fontSize: 14, color: colors.muted, marginBottom: 20 },
        inputRow: { flexDirection: "row", gap: 12, marginBottom: 12 },
        inputGroup: { flex: 1 },
        inputLabel: { fontSize: 11, fontWeight: "700", color: colors.muted, marginBottom: 6, letterSpacing: 0.5 },
        input: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 12, fontSize: 18, fontWeight: "700", textAlign: "center" },
        updateButton: { backgroundColor: colors.primary, borderRadius: 12, paddingVertical: 12, alignItems: "center", marginBottom: 20 },
        updateButtonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "700" },
        gaugeContainer: { alignItems: "center", marginBottom: 20, position: "relative" },
        bmiValueContainer: { position: "absolute", bottom: 0, alignItems: "center" },
        bmiValue: { fontSize: 40, fontWeight: "900" },
        bmiLabel: { fontSize: 13, color: colors.muted, fontWeight: "600" },
        categoryCard: { borderRadius: 16, padding: 20, alignItems: "center", marginBottom: 16, borderWidth: 1.5 },
        categoryEmoji: { fontSize: 36, marginBottom: 8 },
        categoryLabel: { fontSize: 20, fontWeight: "800", marginBottom: 4 },
        categoryRange: { fontSize: 13, color: colors.muted, marginBottom: 8 },
        categoryDescription: { fontSize: 14, color: colors.foreground, textAlign: "center", lineHeight: 20 },
        idealWeightCard: { backgroundColor: colors.surface, borderRadius: 16, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: colors.border, alignItems: "center" },
        idealWeightTitle: { fontSize: 15, fontWeight: "700", color: colors.foreground, marginBottom: 4 },
        idealWeightValue: { fontSize: 24, fontWeight: "800", color: colors.success, marginBottom: 4 },
        idealWeightSub: { fontSize: 12, color: colors.muted },
        idealWeightDiff: { fontSize: 13, fontWeight: "600", marginTop: 4 },
        adviceCard: { backgroundColor: colors.primary + "10", borderRadius: 16, padding: 16, marginBottom: 16, borderWidth: 1, borderColor: colors.primary + "30" },
        adviceTitle: { fontSize: 15, fontWeight: "700", color: colors.foreground, marginBottom: 8 },
        adviceText: { fontSize: 14, color: colors.foreground, lineHeight: 20 },
        referenceCard: { backgroundColor: colors.surface, borderRadius: 16, overflow: "hidden", borderWidth: 1, borderColor: colors.border },
        referenceTitle: { fontSize: 14, fontWeight: "700", color: colors.muted, padding: 12, paddingBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 },
        referenceRow: { flexDirection: "row", alignItems: "center", paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.border },
        referenceDot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 },
        referenceLabel: { flex: 1, fontSize: 13, color: colors.muted },
        referenceRange: { fontSize: 12, color: colors.muted },
        emptyContainer: { flex: 1, alignItems: "center", justifyContent: "center", padding: 40, paddingTop: 60 },
        emptyEmoji: { fontSize: 64, marginBottom: 16 },
        emptyTitle: { fontSize: 22, fontWeight: "700", color: colors.foreground, marginBottom: 8 },
        emptyText: { fontSize: 15, color: colors.muted, textAlign: "center", lineHeight: 22 },
    });
}