import {
    StyleSheet,
} from "react-native";

export const PetStyles = (colors: any) => {
    return StyleSheet.create({
        scroll: { flex: 1 },
        content: {
            paddingHorizontal: 20,
            paddingTop: 16,
            paddingBottom: 20,
        },
        header: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 16,
        },
        title: {
            fontSize: 24,
            fontWeight: "800",
            color: colors.foreground,
        },
        renameButton: {
            backgroundColor: colors.surface,
            paddingHorizontal: 12,
            paddingVertical: 8,
            borderRadius: 12,
            borderWidth: 1,
            borderColor: colors.border,
        },
        renameButtonText: {
            fontSize: 13,
            color: colors.foreground,
            fontWeight: "600",
        },
        petCard: {
            backgroundColor: colors.surface,
            borderRadius: 20,
            padding: 20,
            marginBottom: 16,
            borderWidth: 2,
            alignItems: "center",
        },
        petDescription: {
            fontSize: 14,
            color: colors.muted,
            textAlign: "center",
            lineHeight: 20,
        },
        evolutionCard: {
            backgroundColor: colors.surface,
            borderRadius: 16,
            padding: 16,
            marginBottom: 16,
            borderWidth: 1,
            borderColor: colors.border,
        },
        evolutionHeader: {
            flexDirection: "row",
            justifyContent: "space-between",
            marginBottom: 8,
        },
        evolutionLabel: {
            fontSize: 14,
            color: colors.muted,
            fontWeight: "600",
        },
        evolutionPercent: {
            fontSize: 14,
            color: colors.primary,
            fontWeight: "700",
        },
        progressBarBg: {
            height: 10,
            backgroundColor: colors.border,
            borderRadius: 5,
            marginBottom: 6,
        },
        progressBarFill: {
            height: 10,
            borderRadius: 5,
        },
        evolutionHint: {
            fontSize: 12,
            color: colors.muted,
        },
        statsGrid: {
            flexDirection: "row",
            marginBottom: 16,
        },
        warningCard: {
            borderRadius: 12,
            padding: 14,
            marginBottom: 16,
            borderWidth: 1,
        },
        warningText: {
            fontSize: 14,
            color: colors.foreground,
            fontWeight: "600",
            textAlign: "center",
        },
        shopCard: {
            backgroundColor: colors.surface,
            borderRadius: 16,
            padding: 16,
            borderWidth: 1,
            borderColor: colors.border,
        },
        shopTitle: {
            fontSize: 17,
            fontWeight: "700",
            color: colors.foreground,
            marginBottom: 4,
        },
        shopSubtitle: {
            fontSize: 13,
            color: colors.muted,
            marginBottom: 12,
        },
        shopRow: {
            flexDirection: "row",
            gap: 8,
        },
        shopButton: {
            flex: 1,
            backgroundColor: colors.background,
            borderRadius: 12,
            padding: 12,
            alignItems: "center",
            borderWidth: 1,
            borderColor: colors.border,
        },
        shopButtonText: {
            fontSize: 13,
            fontWeight: "600",
            color: colors.foreground,
            marginBottom: 4,
        },
        shopPrice: {
            fontSize: 12,
            color: colors.primary,
            fontWeight: "700",
        },
        // Tela de RIP
        ripContainer: {
            flex: 1,
            alignItems: "center",
            paddingTop: 40,
            paddingHorizontal: 24,
        },
        ripEmoji: {
            fontSize: 80,
            marginBottom: 16,
        },
        ripTitle: {
            fontSize: 36,
            fontWeight: "900",
            color: colors.muted,
            letterSpacing: 4,
            marginBottom: 4,
        },
        ripPetName: {
            fontSize: 24,
            fontWeight: "700",
            color: colors.foreground,
            marginBottom: 24,
        },
        ripCard: {
            backgroundColor: colors.surface,
            borderRadius: 16,
            padding: 20,
            width: "100%",
            alignItems: "center",
            marginBottom: 24,
            borderWidth: 1,
            borderColor: colors.border,
        },
        ripReason: {
            fontSize: 13,
            color: colors.muted,
            marginBottom: 8,
            fontWeight: "600",
        },
        ripText: {
            fontSize: 16,
            color: colors.foreground,
            fontWeight: "600",
            textAlign: "center",
            marginBottom: 8,
        },
        ripDays: {
            fontSize: 14,
            color: colors.error,
            fontWeight: "700",
        },
        ripHope: {
            fontSize: 15,
            color: colors.foreground,
            textAlign: "center",
            lineHeight: 24,
        },
        // Modal
        modalOverlay: {
            flex: 1,
            backgroundColor: "rgba(0,0,0,0.5)",
            alignItems: "center",
            justifyContent: "center",
            padding: 24,
        },
        modalCard: {
            backgroundColor: colors.surface,
            borderRadius: 20,
            padding: 24,
            width: "100%",
        },
        modalTitle: {
            fontSize: 20,
            fontWeight: "700",
            color: colors.foreground,
            marginBottom: 16,
            textAlign: "center",
        },
        modalInput: {
            backgroundColor: colors.background,
            borderWidth: 1,
            borderColor: colors.border,
            borderRadius: 12,
            padding: 14,
            fontSize: 16,
            color: colors.foreground,
            marginBottom: 16,
        },
        modalButtons: {
            flexDirection: "row",
            gap: 12,
        },
        modalButton: {
            flex: 1,
            paddingVertical: 14,
            borderRadius: 12,
            alignItems: "center",
        },
        modalButtonText: {
            fontSize: 15,
            fontWeight: "700",
        },
        adBanner: { maxHeight: 180, backgroundColor: colors.surface, borderTopWidth: 1, borderTopColor: colors.border, alignItems: "center", justifyContent: "center" },
    });
}
